package com.battalion.flashpoint.core 
{
	import flash.geom.Point;
	/**
	 * A contact point, generated by the physics engine, PowerGrid.
	 * @author Battalion Chiefs
	 */
	public final class ContactPoint 
	{
		
		public var point : Point;
		public var normal : Point;
		public var relativeVelocity : Point;
		
		/*
		public var thisCollider : Collider;
		public var otherCollider : Collider;
		*/
		public var friction : Number;
		public var bounce : Number;
		public var separation : Number;
		
	}

}