package com.battalion.flashpoint.core 
{
	import flash.geom.Point;
	import com.battalion.powergrid.Contact;
	/**
	 * A contact point, generated by the physics engine, PowerGrid.
	 * @author Battalion Chiefs
	 */
	public final class ContactPoint 
	{
		
		public var point : Point;
		public var normal : Point;
		
		//public var relativeVelocity : Point;
		
		public var thisCollider : Collider;
		public var otherCollider : Collider;
		
		/*
		public var friction : Number;
		public var bounce : Number;
		public var separation : Number;
		*/
		public function ContactPoint(contact : Contact = null)
		{
			if (contact)
			{
				point = new Point(contact.x, contact.y);
				normal = new Point(contact.nx, contact.ny);
				
				thisCollider = contact.thisBody.userData as Collider;
				otherCollider = contact.other.thisBody.userData as Collider;
			}
		}
		
	}

}